###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mysql:
        image: 'mysql:8.0'
        working_dir: /arons
        volumes:
            - '.:/arons'
            - ./phpdocker/mysql:/docker-entrypoint-initdb.d
            - ./phpdocker/mysql/data:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
        ports:
            - '3002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /arons
        volumes:
            - '.:/arons'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '3000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /arons
        volumes:
            - '.:/arons'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        ports:
            - "9000:9000"
